language: php

# We use trusty as currently there is an issue with java and moodle-plugin-ci mustache linting which
# causes causes tests to fail on xenial and bionic. (See https://github.com/blackboard-open-source/moodle-plugin-ci/issues/91).
dist: xenial

addons:
  firefox: latest
  chrome: stable
  postgresql: "9.6"

services:
  - mysql

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
env:
  global:
    - MOODLE_BRANCH=master
    - IGNORE_PATHS=tests/fixtures
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - DB=pgsql MOODLE_BRANCH=master
    - DB=mysqli MOODLE_BRANCH=master

dist: xenial

matrix:
  exclude:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.1
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.3
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - sudo apt-get update
  - phpenv config-rm xdebug.ini
  - if [ "$MOODLE_VERSION" = 36 ] || [ "$MOODLE_VERSION" -le 34 ]; then NVMVERSION=8.9; else NVMVERSION=14.0.0; fi
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci dev-master
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
# Grunt is currently broken due to a new way of building JS on 3.8+
#  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
